# Generated by Django 3.1.2 on 2020-10-09 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbID', models.CharField(max_length=255, unique=True, verbose_name='imdb_id')),
                ('title', models.CharField(max_length=1000, verbose_name='title')),
                ('year', models.IntegerField(verbose_name='year')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('poster', models.URLField(verbose_name='poster')),
                ('users', models.ManyToManyField(blank=True, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
