# Generated by Django 3.1.2 on 2020-10-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='Year',
        ),
    ]
