# Generated by Django 3.1.2 on 2020-10-11 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_omdb_viewset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.CharField(max_length=1000, verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Year',
            field=models.CharField(max_length=255, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='users',
            field=models.ManyToManyField(related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
